pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/rajashreey841/Jenkins.git'
            }
        }

        stage('Run Python Script') {
            steps {
                sh 'python3 hello_world.py'
            }
        }
    }
}

